#SITE CONFIGURATION

title: Gordon Cortney
description: Musicologist Detective 
repository: "https://gmcortney.github.io/music-portfolio--Cortney/"
baseurl: 
url: "https://gmcortney.github.io/music-portfolio--Cortney/"

google_tag_manager: GTM-P7PZFVP

# SEO PLUGIN

social:
  name: Gordon Cortney
  links:
    - https://www.facebook.com/gordoncortney
    - https://www.instagram.com/gordoncortney3
    - https://www.youtube.com/user/gmcortney
    - https://github.com/andrewstiefel
    
#THEME SETTINGS

navigation: # Navigation links
  - {name: 'Music', link: '/music'}
  - {name: 'Recordings', link: '/recordings'}
  - {name: 'Contact', link: '/contact'}
  
email: andrew@andrewstiefel.com
twitter_username: andrewstiefel
github_username: andrewstiefel
instagram_username: andrewstiefel
facebook_username: andrewstiefel
linkedin_username: andrewstiefel

#BUILD SETTINGS

markdown: kramdown
include: ['_pages']
permalink: /blog/:title

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

compress_html:
  clippings: all

plugins: 
  - jekyll-sitemap
  - jekyll-seo-tag
